const INITIAL_INVENTORY = [
  { id: 'item_1', category: 'FOOD & MEAT ITEMS', name: 'Chicken Burger', innerDetails: '1 inner (40 pcs)', caseDetails: '1 case (8 inner)', lidInfo: 'N/A' },
  { id: 'item_2', category: 'FOOD & MEAT ITEMS', name: 'Grilled Chicken', innerDetails: '1 inner (40 pcs)', caseDetails: '1 case 8 inner', lidInfo: 'N/A' },
  { id: 'item_3', category: 'FOOD & MEAT ITEMS', name: 'Suages', innerDetails: '1 inner (40 pcs)', caseDetails: '8 inner', lidInfo: 'N/A' },
  { id: 'item_4', category: 'FOOD & MEAT ITEMS', name: 'Chicken Strips', innerDetails: '1 inner (39 pcs)', caseDetails: '8 inner', lidInfo: 'N/A' },
  { id: 'item_5', category: 'FOOD & MEAT ITEMS', name: 'Chicken Nuggets', innerDetails: '1 inner (50 pcs)', caseDetails: '1 case (18 inner)', lidInfo: 'N/A' },
  { id: 'item_6', category: 'FOOD & MEAT ITEMS', name: 'Jalapeno', innerDetails: '1 inner (48 pcs)', caseDetails: '1 case (6 inner)', lidInfo: 'N/A' },
  { id: 'item_7', category: 'FOOD & MEAT ITEMS', name: 'Crispy High Crunch', innerDetails: '1 inner (8 pcs)', caseDetails: '1 case (12 inner)', lidInfo: 'N/A' },
  { id: 'item_8', category: 'FOOD & MEAT ITEMS', name: 'Grand Chicken', innerDetails: '1 inner (20 pcs)', caseDetails: '1 case (6 inner)', lidInfo: 'N/A' },
  { id: 'item_9', category: 'FOOD & MEAT ITEMS', name: 'Grand Chicken Spicy', innerDetails: '1 inner (20 pcs)', caseDetails: '1 case (6 inner)', lidInfo: 'N/A' },
  { id: 'item_10', category: 'FOOD & MEAT ITEMS', name: 'Mc Chicken', innerDetails: '1 inner (27 pcs)', caseDetails: '1 case (8 inner)', lidInfo: 'N/A' },
  { id: 'item_11', category: 'FOOD & MEAT ITEMS', name: 'Mc Chicken Spicy', innerDetails: '1 inner (27 pcs)', caseDetails: '1 case (8 inner)', lidInfo: 'N/A' },
  { id: 'item_12', category: 'FOOD & MEAT ITEMS', name: '10:1 beef', innerDetails: 'N/A', caseDetails: '1 case 300 pcs', lidInfo: 'N/A' },
  { id: 'item_13', category: 'FOOD & MEAT ITEMS', name: '4:1 beef', innerDetails: 'N/A', caseDetails: '1 case 120 pcs', lidInfo: 'N/A' },
  { id: 'item_14', category: 'FOOD & MEAT ITEMS', name: '3:1 beef', innerDetails: 'N/A', caseDetails: '1 case 90 pcs', lidInfo: 'N/A' },
  { id: 'item_15', category: 'FOOD & MEAT ITEMS', name: 'Regular Bun', innerDetails: '1 inner (30 pcs)', caseDetails: '1 case (2 inner)', lidInfo: 'N/A' },
  { id: 'item_16', category: 'FOOD & MEAT ITEMS', name: 'Quarter Bun', innerDetails: '2 inner (30 pcs)', caseDetails: '1 case (2 inner)', lidInfo: 'N/A' },
  { id: 'item_17', category: 'FOOD & MEAT ITEMS', name: 'Bigmac Bun', innerDetails: 'N/A', caseDetails: '1 case 30 pcs', lidInfo: 'N/A' },
  { id: 'item_18', category: 'FOOD & MEAT ITEMS', name: 'Big tasty Bun', innerDetails: '1 inner 20 pcs', caseDetails: '1 case 2 inner', lidInfo: 'N/A' },
  { id: 'item_19', category: 'FOOD & MEAT ITEMS', name: 'Water split bun', innerDetails: '1 inner 20 pcs', caseDetails: '1 case 2 inner', lidInfo: 'N/A' },
  { id: 'item_20', category: 'FOOD & MEAT ITEMS', name: 'Hash brown', innerDetails: '1 inner 25 pcs', caseDetails: '1 case (6 inner)', lidInfo: 'N/A' },
  { id: 'item_21', category: 'FOOD & MEAT ITEMS', name: 'English muffin', innerDetails: '1 inner 12 pcs', caseDetails: '1 case 8 inner', lidInfo: 'N/A' },
  { id: 'item_22', category: 'FOOD & MEAT ITEMS', name: 'fajita chicken strips', innerDetails: '1 inner 17.62 oz', caseDetails: '1 case 20 inner', lidInfo: 'N/A' },

  { id: 'item_23', category: 'BEVERAGES & CONDIMENTS', name: 'Orange + Apple Juice', innerDetails: '1 inner (4.5 Liter)', caseDetails: 'Case 1 inner / 3 inner', lidInfo: 'N/A' },
  { id: 'item_24', category: 'BEVERAGES & CONDIMENTS', name: 'Ketchup Pack', innerDetails: 'N/A', caseDetails: '1 case (1892 pcs)', lidInfo: 'N/A' },
  { id: 'item_25', category: 'BEVERAGES & CONDIMENTS', name: 'Ketchup Pouch', innerDetails: '1 inner (1 kg)', caseDetails: '1 case (15 inner)', lidInfo: 'N/A' },
  { id: 'item_26', category: 'BEVERAGES & CONDIMENTS', name: 'Mustard', innerDetails: '1 inner (1 kg)', caseDetails: '1 case (24 inner)', lidInfo: 'N/A' },
  { id: 'item_27', category: 'BEVERAGES & CONDIMENTS', name: 'Cheddar + Mental', innerDetails: '1 inner (2.27 kg / 160 pcs)', caseDetails: '1 case (8 inner)', lidInfo: 'N/A' },
  { id: 'item_28', category: 'BEVERAGES & CONDIMENTS', name: 'Periperi Sauce Pouch', innerDetails: 'N/A', caseDetails: '1 case (24 inner)', lidInfo: 'N/A' },
  { id: 'item_29', category: 'BEVERAGES & CONDIMENTS', name: 'All Pouch Sauce', innerDetails: '30 inner', caseDetails: 'N/A', lidInfo: 'N/A' },
  { id: 'item_30', category: 'BEVERAGES & CONDIMENTS', name: 'All Sauce Cups', innerDetails: 'N/A', caseDetails: '1 case (288 pcs)', lidInfo: 'N/A' },
  { id: 'item_31', category: 'BEVERAGES & CONDIMENTS', name: 'Regular Ice Cream Cone', innerDetails: 'N/A', caseDetails: '1 case (952 pcs)', lidInfo: 'N/A' },
  { id: 'item_32', category: 'BEVERAGES & CONDIMENTS', name: 'Oreo Pieces', innerDetails: '1 inner (454 g)', caseDetails: '1 case (24 inner)', lidInfo: 'N/A' },

  { id: 'item_33', category: 'CUPS, LIDS & PACKAGING (PAPER)', name: 'Regular 16oz Cold Cup', innerDetails: '60 pcs', caseDetails: '20 inner', lidInfo: '135 pcs' },
  { id: 'item_34', category: 'CUPS, LIDS & PACKAGING (PAPER)', name: 'Medium 22oz Cold Cup', innerDetails: '65 pcs', caseDetails: '20 inner', lidInfo: '135 pcs' },
  { id: 'item_35', category: 'CUPS, LIDS & PACKAGING (PAPER)', name: 'Large 32oz Cold Cup', innerDetails: '40 pcs', caseDetails: '20 inner', lidInfo: '100 pcs' },
  { id: 'item_36', category: 'CUPS, LIDS & PACKAGING (PAPER)', name: 'Small 12oz Cold Cup', innerDetails: '90 pcs', caseDetails: '24 inner', lidInfo: '140 pcs' },
  { id: 'item_37', category: 'CUPS, LIDS & PACKAGING (PAPER)', name: 'Oreo Cup', innerDetails: '35 pcs', caseDetails: '20 pcs (Case)', lidInfo: 'N/A' },
  { id: 'item_38', category: 'CUPS, LIDS & PACKAGING (PAPER)', name: 'Sunde Cup', innerDetails: '50 pcs', caseDetails: 'N/A', lidInfo: '1 inner (50 pcs)' },
  { id: 'item_39', category: 'CUPS, LIDS & PACKAGING (PAPER)', name: '10 oz Clear Cup', innerDetails: '50 pcs', caseDetails: '20 inner', lidInfo: '100 pcs (10 inner case)' },
  { id: 'item_40', category: 'CUPS, LIDS & PACKAGING (PAPER)', name: '14oz Clear Cup', innerDetails: '50 pcs', caseDetails: '20 inner', lidInfo: '100 pcs (10 inner case)' },
  { id: 'item_41', category: 'CUPS, LIDS & PACKAGING (PAPER)', name: 'Small Fries', innerDetails: '500 pcs', caseDetails: '8,000 pcs 16 inner', lidInfo: 'N/A' },
  { id: 'item_42', category: 'CUPS, LIDS & PACKAGING (PAPER)', name: 'Medium Fries', innerDetails: 'N/A', caseDetails: '2,000 pcs', lidInfo: 'N/A' },
  { id: 'item_43', category: 'CUPS, LIDS & PACKAGING (PAPER)', name: 'Large Fries', innerDetails: 'N/A', caseDetails: '1,200 pcs', lidInfo: 'N/A' },
  { id: 'item_44', category: 'CUPS, LIDS & PACKAGING (PAPER)', name: 'Regular Fries', innerDetails: 'N/A', caseDetails: '1,200 pcs', lidInfo: 'N/A' },
  { id: 'item_45', category: 'CUPS, LIDS & PACKAGING (PAPER)', name: 'E Bag', innerDetails: 'N/A', caseDetails: '250 pcs', lidInfo: 'N/A' },
  { id: 'item_46', category: 'CUPS, LIDS & PACKAGING (PAPER)', name: 'B Bag', innerDetails: 'N/A', caseDetails: '1,000 pcs', lidInfo: 'N/A' },
  { id: 'item_47', category: 'CUPS, LIDS & PACKAGING (PAPER)', name: 'C Bag', innerDetails: 'N/A', caseDetails: '1,000 pcs', lidInfo: 'N/A' },
  { id: 'item_48', category: 'CUPS, LIDS & PACKAGING (PAPER)', name: 'A Bag', innerDetails: 'N/A', caseDetails: '2,000 pcs', lidInfo: 'N/A' },
  { id: 'item_49', category: 'CUPS, LIDS & PACKAGING (PAPER)', name: 'Happy Meal Carton', innerDetails: 'N/A', caseDetails: '350 pcs', lidInfo: 'N/A' },
  { id: 'item_50', category: 'CUPS, LIDS & PACKAGING (PAPER)', name: 'Napkin', innerDetails: '250 pcs', caseDetails: 'N/A', lidInfo: 'N/A' },
  { id: 'item_51', category: 'CUPS, LIDS & PACKAGING (PAPER)', name: 'Straw', innerDetails: '250 pcs', caseDetails: 'N/A', lidInfo: 'N/A' },
  { id: 'item_52', category: 'CUPS, LIDS & PACKAGING (PAPER)', name: '4 cup carrier', innerDetails: 'N/A', caseDetails: '1 case 300 pcs', lidInfo: 'N/A' },
  { id: 'item_53', category: 'CUPS, LIDS & PACKAGING (PAPER)', name: '2 cup carrier', innerDetails: 'N/A', caseDetails: '1 case 600 pcs', lidInfo: 'N/A' },
  { id: 'item_54', category: 'CUPS, LIDS & PACKAGING (PAPER)', name: 'spon', innerDetails: 'N/A', caseDetails: '1 case', lidInfo: 'N/A' },
];

window.INITIAL_INVENTORY = INITIAL_INVENTORY;
